"""added bestseller field in product

Revision ID: 1246560d3cff
Revises: ccc7a1431263
Create Date: 2026-08-18 06:25:51.438032

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1246560d3cff"
down_revision: str | Sequence[str] | None = "ccc7a1431263"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products", "is_best_seller", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.drop_constraint(op.f("reviews_product_id_fkey"), "reviews", type_="foreignkey")
    op.create_foreign_key(
        None, "reviews", "products", ["product_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.create_foreign_key(
        op.f("reviews_product_id_fkey"), "reviews", "products", ["product_id"], ["id"]
    )
    op.alter_column(
        "products", "is_best_seller", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###
