"""Delivery rule table

Revision ID: 2a36f1d8db5c
Revises: 0c4078007e49
Create Date: 2026-09-19 08:11:05.592326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a36f1d8db5c'
down_revision: Union[str, Sequence[str], None] = '0c4078007e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_channel',
               existing_type=postgresql.ENUM('app', 'phone', 'walk_in', name='order_channel'),
               nullable=True,
               existing_server_default=sa.text("'app'::order_channel"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_channel',
               existing_type=postgresql.ENUM('app', 'phone', 'walk_in', name='order_channel'),
               nullable=False,
               existing_server_default=sa.text("'app'::order_channel"))
    # ### end Alembic commands ###
