"""pmt intent id

Revision ID: 5b26fc4b0bfa
Revises: a069ceeec9bd
Create Date: 2026-09-06 04:15:50.116372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b26fc4b0bfa'
down_revision: Union[str, Sequence[str], None] = 'a069ceeec9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_intent_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'payments', ['payment_intent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'payment_intent_id')
    # ### end Alembic commands ###
