"""payment intent-id fixed

Revision ID: 69329aca4681
Revises: b3ac7c483e06
Create Date: 2026-09-10 11:41:44.235774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69329aca4681'
down_revision: Union[str, Sequence[str], None] = 'b3ac7c483e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stripe_events', 'payment_intent_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('stripe_events_payment_intent_id_key'), 'stripe_events', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('stripe_events_payment_intent_id_key'), 'stripe_events', ['payment_intent_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('stripe_events', 'payment_intent_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
