"""datetime aware for scheduled time in delivery-details model

Revision ID: 7280d7c47490
Revises: 5b26fc4b0bfa
Create Date: 2026-09-06 12:36:34.708558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7280d7c47490'
down_revision: Union[str, Sequence[str], None] = '5b26fc4b0bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
