"""image table created

Revision ID: 7d9e6524ac9c
Revises: 5372494fe426
Create Date: 2026-08-02 09:36:47.749209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9e6524ac9c'
down_revision: Union[str, Sequence[str], None] = '5372494fe426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'main_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'main_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
