"""added review title and description

Revision ID: 91b362b3debf
Revises: 946e193c1df3
Create Date: 2026-08-24 00:25:15.016039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b362b3debf'
down_revision: Union[str, Sequence[str], None] = '946e193c1df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_title', sa.String(), nullable=False))
    op.add_column('reviews', sa.Column('review_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'review_description')
    op.drop_column('reviews', 'review_title')
    # ### end Alembic commands ###
