"""reconfigured cascade delete for review table and added grouped unit field in product model

Revision ID: 946e193c1df3
Revises: bf414cefdcfc
Create Date: 2026-08-20 04:40:58.971898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946e193c1df3'
down_revision: Union[str, Sequence[str], None] = 'bf414cefdcfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
