"""unique contraint removed from session for device id

Revision ID: 95bd2685d98c
Revises: f86c7234b026
Create Date: 2026-07-30 10:48:26.151308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95bd2685d98c'
down_revision: Union[str, Sequence[str], None] = 'f86c7234b026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sessions_device_id_key'), 'sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('sessions_device_id_key'), 'sessions', ['device_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
