"""init

Revision ID: 99dd5754567a
Revises: 652047d2c002
Create Date: 2026-08-02 03:30:45.824475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99dd5754567a'
down_revision: Union[str, Sequence[str], None] = '652047d2c002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sold_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sold_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
