"""coupen code unque and index based

Revision ID: a069ceeec9bd
Revises: f92cd2be4b05
Create Date: 2026-09-06 03:06:13.803184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a069ceeec9bd'
down_revision: Union[str, Sequence[str], None] = 'f92cd2be4b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_coupens_code'), 'coupens', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coupens_code'), table_name='coupens')
    # ### end Alembic commands ###
