"""init

Revision ID: a89ff0e5fa71
Revises: 3a8b43a247fb
Create Date: 2026-08-02 09:03:24.302957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89ff0e5fa71'
down_revision: Union[str, Sequence[str], None] = '3a8b43a247fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_product', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('category_product', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_product', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('category_product', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
