"""added bestseller field in product

Revision ID: ccc7a1431263
Revises: b0d4a65df68e
Create Date: 2026-08-18 06:21:49.756650

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccc7a1431263"
down_revision: str | Sequence[str] | None = "b0d4a65df68e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("is_best_seller", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "is_best_seller")
    # ### end Alembic commands ###
