"""Delivery rule table

Revision ID: e76c29be7418
Revises: 2a36f1d8db5c
Create Date: 2026-09-19 08:22:46.783549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76c29be7418'
down_revision: Union[str, Sequence[str], None] = '2a36f1d8db5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_rules',
    sa.Column('start_km', sa.Integer(), nullable=False),
    sa.Column('end_km', sa.Integer(), nullable=False),
    sa.Column('delivery_thresold', sa.Integer(), nullable=False),
    sa.Column('delivery_fee', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_rules')
    # ### end Alembic commands ###
