"""added bestseller field in product

Revision ID: f00e14676a01
Revises: 1246560d3cff
Create Date: 2026-08-18 06:27:53.572544

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f00e14676a01"
down_revision: str | Sequence[str] | None = "1246560d3cff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("comments_review_id_fkey"), "comments", type_="foreignkey")
    op.create_foreign_key(
        None, "comments", "reviews", ["review_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "products", "is_best_seller", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products", "is_best_seller", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        op.f("comments_review_id_fkey"), "comments", "reviews", ["review_id"], ["id"]
    )
    # ### end Alembic commands ###
