"""removed unique user key from session table

Revision ID: f86c7234b026
Revises: 66ef6bba039f
Create Date: 2026-07-23 09:23:33.792945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f86c7234b026'
down_revision: Union[str, Sequence[str], None] = '66ef6bba039f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sessions_user_id_key'), 'sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('sessions_user_id_key'), 'sessions', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
