"""delivery model created for order

Revision ID: f92cd2be4b05
Revises: d91184825f1f
Create Date: 2026-09-05 08:44:43.399832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92cd2be4b05'
down_revision: Union[str, Sequence[str], None] = 'd91184825f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_details',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('receiptent_name', sa.String(), nullable=False),
    sa.Column('receiptent_phone', sa.String(), nullable=False),
    sa.Column('delivery_address', sa.String(), nullable=False),
    sa.Column('delivery_landmark', sa.String(), nullable=True),
    sa.Column('delivery_timing', sa.Enum('ASAP', 'SCHEDULED', name='delivery_timing_status'), nullable=False),
    sa.Column('delivery_note', sa.String(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_details')
    # ### end Alembic commands ###
